"""
Bhoomi Mitra – RTI Document Generation Route
POST /api/v1/documents/rti-draft
POST /api/v1/documents/sale-checklist

Generates legally-structured RTI applications and pre-sale verification
checklists for Indian citizens in plain English + Hinglish.
"""
from __future__ import annotations
from datetime import date
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Optional
from app.auth import get_current_user
from app.services.govt_api_mock import fetch_land_record, fetch_court_disputes

router = APIRouter(prefix="/api/v1/documents", tags=["Documents"])


class RTIRequest(BaseModel):
    land_code: str
    applicant_name: str
    applicant_address: str


class ChecklistRequest(BaseModel):
    land_code: str


# ── RTI Draft Generator ───────────────────────────────────────────────────
@router.post("/rti-draft", summary="Generate RTI application for a land parcel")
def generate_rti_draft(
    body: RTIRequest,
    _user: dict = Depends(get_current_user),
):
    record = fetch_land_record(body.land_code)
    if not record:
        raise HTTPException(status_code=404, detail=f"Parcel '{body.land_code}' not found.")

    disputes = fetch_court_disputes(body.land_code)
    today = date.today().strftime("%d %B %Y")

    rti_text = f"""
RIGHT TO INFORMATION ACT, 2005 – APPLICATION FORM

To,
The Public Information Officer (PIO),
Office of the Sub-Registrar / Revenue Department,
[District / Tehsil to be filled based on parcel location]

Date: {today}

Subject: Application for information under the Right to Information Act, 2005
         regarding Land Parcel – Bhu-Aadhar ID {body.land_code}

Sir/Madam,

I, {body.applicant_name}, residing at {body.applicant_address}, hereby request
the following information under Section 6 of the Right to Information Act, 2005:

1. LAND RECORD DETAILS
   a) Certified copy of the latest Khatauni / Record of Rights (RoR) for plot
      bearing Bhu-Aadhar (ULPIN) ID: {body.land_code}
   b) Name(s) of all recorded owners and co-owners as per current revenue register.
   c) Complete mutation history (Dakhil-Kharij records) for the last 10 years.

2. SURVEY & DEMARCATION
   a) Date and findings of the last conducted cadastral survey for this plot.
   b) Status of any pending re-survey or boundary dispute inquiry.
   c) Certified copy of the Shajra / field map showing plot boundaries.

3. ENCUMBRANCE INFORMATION
   a) Whether any mortgage, lien, charge, or court attachment exists on this parcel.
   b) Details of any No-Objection Certificate (NOC) conditions from Irrigation,
      Forest, or National Highway departments.
   c) Copy of any stay order or injunction issued by a court against this parcel.

4. GIS & LAND USE
   a) Current land-use classification (agricultural / residential / commercial).
   b) Whether this parcel falls within any buffer zone of a National Highway,
      Railway corridor, forest reserve, or eco-sensitive zone.

{'5. COURT CASE DETAILS' if disputes else ''}
{'   a) Full details of case number(s): ' + ', '.join([d["case_number"] for d in disputes]) if disputes else ''}
{'   b) Current status, last hearing date, and next date of case.' if disputes else ''}

PAYMENT: Application fee of ₹10 has been enclosed/paid as per RTI Act.

I request that the information be provided within the statutory period of 30 days
as mandated by the Right to Information Act, 2005.

Yours faithfully,

{body.applicant_name}
{body.applicant_address}
Contact: [Your Mobile Number]
Date: {today}

---
[Generated by Bhoomi Mitra · Pratyaksh AI Citizen Portal]
[Reference: Bhu-Aadhar ID {body.land_code}]
""".strip()

    return {
        "land_code": body.land_code,
        "document_type": "RTI_Application",
        "generated_on": today,
        "content": rti_text,
        "word_count": len(rti_text.split()),
        "language": "English",
        "instructions": (
            "Print on plain A4 paper. Attach ₹10 IPO/Court Fee Stamp as RTI application fee. "
            "Submit at your district Sub-Registrar Office or upload via RTIOnline portal (www.rtionline.gov.in)."
        ),
    }


# ── Pre-Sale Verification Checklist ─────────────────────────────────────────
@router.post("/sale-checklist", summary="Generate pre-sale verification checklist")
def generate_sale_checklist(
    body: ChecklistRequest,
    _user: dict = Depends(get_current_user),
):
    record = fetch_land_record(body.land_code)
    if not record:
        raise HTTPException(status_code=404, detail=f"Parcel '{body.land_code}' not found.")

    disputes = fetch_court_disputes(body.land_code)
    has_dispute = bool(disputes)

    checklist = [
        {
            "category": "Legal Title Verification",
            "items": [
                {"task": "Verify Khatauni (Record of Rights) for current ownership", "priority": "Critical", "done": False},
                {"task": "Check 30-year chain of title documents", "priority": "Critical", "done": False},
                {"task": "Verify seller's identity with Aadhaar + PAN", "priority": "Critical", "done": False},
                {"task": "Obtain Encumbrance Certificate (EC) for last 30 years", "priority": "Critical", "done": False},
            ]
        },
        {
            "category": "Court & Litigation Check",
            "items": [
                {
                    "task": f"Active court case detected: {disputes[0]['case_number']} — Obtain legal clearance before proceeding",
                    "priority": "Urgent",
                    "done": False
                } if has_dispute else {
                    "task": "Confirm nil litigation via e-Courts portal search",
                    "priority": "High",
                    "done": not has_dispute
                },
                {"task": "Check for any injunctions or stay orders at Sub-Divisional Court", "priority": "High", "done": False},
            ]
        },
        {
            "category": "Government Permissions & NOCs",
            "items": [
                {"task": "Obtain NOC from Irrigation Department (if near river/canal)", "priority": "High", "done": False},
                {"task": "Verify National Highway buffer clearance (NHAI)", "priority": "High", "done": False},
                {"task": "Check Forest Department clearance (if near reserve forest)", "priority": "High", "done": False},
                {"task": "Obtain conversion order if agricultural land used for non-ag purpose", "priority": "Critical", "done": False},
            ]
        },
        {
            "category": "Financial Verification",
            "items": [
                {"task": "Verify circle rate at Sub-Registrar Office to detect under-valuation", "priority": "Medium", "done": False},
                {"task": "Confirm no outstanding land revenue / tax dues", "priority": "High", "done": False},
                {"task": "Negotiate stamp duty & registration charges (buyer responsibility)", "priority": "Medium", "done": False},
            ]
        },
        {
            "category": "Physical Verification",
            "items": [
                {"task": "Conduct physical boundary demarcation with Revenue Patwari", "priority": "High", "done": False},
                {"task": "Verify actual land dimensions match cadastral records", "priority": "High", "done": False},
                {"task": "Check for encroachments or disputed boundaries with neighbours", "priority": "Medium", "done": False},
            ]
        },
        {
            "category": "Post-Purchase Registration",
            "items": [
                {"task": "Execute & register Sale Deed at Sub-Registrar Office within 4 months", "priority": "Critical", "done": False},
                {"task": "Apply for Dakhil-Kharij (Mutation) within 30 days of registration", "priority": "Critical", "done": False},
                {"task": "Update Khatauni with new owner name at Tehsil office", "priority": "High", "done": False},
            ]
        },
    ]

    total = sum(len(cat["items"]) for cat in checklist)
    urgent_count = sum(
        1 for cat in checklist for item in cat["items"]
        if item["priority"] in ("Critical", "Urgent")
    )

    return {
        "land_code": body.land_code,
        "document_type": "Pre_Sale_Verification_Checklist",
        "parcel_summary": {
            "owner": record["owner_details"]["name"],
            "area": record["land_profile"]["area_acres"],
            "land_type": record["land_profile"]["land_type"],
            "survey_status": record["land_profile"]["survey_status"],
            "has_active_disputes": has_dispute,
        },
        "checklist": checklist,
        "statistics": {
            "total_tasks": total,
            "urgent_or_critical": urgent_count,
            "estimated_completion_days": 30 if not has_dispute else 60,
        },
    }
